/**
 * The block.
 *
 * The PHPUnit suite already proves the render callback returns the same markup
 * the shortcode returns, and that a section contributed through
 * wp_stats_sections reaches both, so repeating any of that here would buy
 * nothing. What only a browser can answer is whether the *built* JavaScript
 * works: build/ is generated by bin/build and is not in the repository, so every
 * assertion below is also an assertion that the build ran and produced something
 * a browser can load.
 *
 * Two things are worth a browser, and nothing else here is:
 *
 * * the editor script loads and registers the block -- a broken build, a missing
 *   dependency in index.asset.php or a bad block.json all show up here and
 *   nowhere else;
 * * a page holding the block renders the statistics page to a visitor, which is
 *   markup that arrived by a different route from the shortcode's.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );
const {
	asGuest,
	installSections,
	removeSections,
	resetOptions,
	setAllToggles,
	uniqueTitle,
} = require( './helpers.js' );

/** The one block this plugin registers. */
const STATS_BLOCK = 'wp-stats/page-stats';

test.describe( 'The block', () => {
	test.beforeEach( async () => {
		resetOptions();
		setAllToggles( 1 );
	} );

	test.afterEach( async () => {
		removeSections();
		resetOptions();
	} );

	test.describe( 'in the editor', () => {
		test( 'it is registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and the name
			// is not here -- which is the failure this whole file exists for.
			expect( names ).toContain( STATS_BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'stats/page-stats' );
		} );

		test( 'it previews the statistics page', async ( { admin, editor } ) => {
			await admin.createNewPost();
			await editor.insertBlock( { name: STATS_BLOCK } );

			// The preview is core's ServerSideRender, which posts to
			// /wp/v2/block-renderer/ and draws what the front end would draw.
			// Seeing the page here is what proves the block earns no REST route
			// of its own.
			await expect(
				editor.canvas.locator( '.wp-stats #GeneralStats' ),
			).toBeVisible();
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a page holding the block renders the statistics page', async ( {
			page,
			requestUtils,
		} ) => {
			// A contributor is installed for this one, because the sections are
			// the half of the page WP-Stats does not own: they arrive through
			// the wp_stats_sections filter from whichever companion plugins are
			// installed, and a block that collected them itself would show a
			// visitor something the shortcode does not.
			installSections( [
				{ key: 'wp_alpha', title: 'Alpha Stats', priority: 10 },
			] );

			const statsPage = await requestUtils.createPage( {
				title: uniqueTitle( 'Statistics in a block' ),
				content: `<!-- wp:${ STATS_BLOCK } /-->`,
				status: 'publish',
			} );

			await asGuest( page, {}, async ( guest ) => {
				await guest.goto( statsPage.link );

				await expect( guest.locator( '.wp-stats' ) ).toBeVisible();
				await expect( guest.locator( '#GeneralStats' ) ).toBeVisible();
				await expect( guest.locator( '.e2e-body-wp_alpha' ) ).toHaveText(
					'body of wp_alpha',
				);
			} );
		} );

		test( 'the block and the shortcode render the same page side by side', async ( {
			page,
			requestUtils,
		} ) => {
			const statsPage = await requestUtils.createPage( {
				title: uniqueTitle( 'Both entry points at once' ),
				content: `<!-- wp:${ STATS_BLOCK } /-->\n\n[page_stats]`,
				status: 'publish',
			} );

			await asGuest( page, {}, async ( guest ) => {
				await guest.goto( statsPage.link );

				// Two wrappers, because both entry points drew the page. Two is
				// what proves the shortcode still works with a block on the same
				// page, which is the promise the whole design rests on.
				await expect( guest.locator( '.wp-stats' ) ).toHaveCount( 2 );
			} );
		} );
	} );
} );
